package main

import (
	"bytes"
	"flag"
	"fmt"
	"io/ioutil"
	"os"
	"os/signal"
	"path/filepath"
	"runtime"
	"strings"
	"sync"
	"syscall"
	"time"

	ignore "github.com/codeskyblue/dockerignore"
	"github.com/codeskyblue/kexec"
	"github.com/gobuild/log"
	"github.com/howeyc/fsnotify"
	yaml "gopkg.in/yaml.v2"
)

const FWCONFIG = ".fwc.yml"

var (
	VERSION = "2.0"
)

var signalMaps = map[string]os.Signal{
	"INT":  syscall.SIGINT,
	"HUP":  syscall.SIGHUP,
	"QUIT": syscall.SIGQUIT,
	"TRAP": syscall.SIGTRAP,
	"TERM": syscall.SIGTERM,
	"KILL": syscall.SIGKILL, // kill -9
}

func init() {
	for key, val := range signalMaps {
		signalMaps["SIG"+key] = val
		signalMaps[fmt.Sprintf("%d", val)] = val
	}
	log.SetFlags(0)
	if runtime.GOOS == "windows" {
		log.SetPrefix("fswatch >>> ")
	} else {
		log.SetPrefix("\033[32mfswatch\033[0m >>> ")
	}
}

const (
	CYELLOW = "33"
	CGREEN  = "32"
	CPURPLE = "35"
)

func CPrintf(ansiColor string, format string, args ...interface{}) {
	if runtime.GOOS != "windows" {
		format = "\033[" + ansiColor + "m" + format + "\033[0m"
	}
	log.Printf(format, args...)
}

type TriggerEvent struct {
	Pattens       []string          `yaml:"pattens"`
	matchPattens  []string          `yaml:"-"`
	Environ       map[string]string `yaml:"env"`
	Command       string            `yaml:"cmd"`
	Delay         string            `yaml:"delay"`
	delayDuration time.Duration     `yaml:"-"`
	Signal        string            `yaml:"signal"`
	killSignal    os.Signal         `yaml:"-"`
	kcmd          *kexec.KCommand
}

func (this *TriggerEvent) Start() error {
	CPrintf(CGREEN, fmt.Sprintf("exec start: %s", this.Command))
	startTime := time.Now()
	cmd := kexec.CommandString(this.Command)
	env := os.Environ()
	for key, val := range this.Environ {
		env = append(env, fmt.Sprintf("%s=%s", key, val))
	}
	cmd.Env = env
	this.kcmd = cmd
	err := cmd.Start()
	go func() {
		if er := cmd.Wait(); er != nil {
			CPrintf(CPURPLE, "program exited: %v", er)
		}
		log.Infof("finish in %s", time.Since(startTime))
	}()
	return err
}

func (this *TriggerEvent) Stop() {
	if this.kcmd != nil {
		if this.kcmd.ProcessState != nil && this.kcmd.ProcessState.Exited() {
			this.kcmd = nil
			return
		}
		this.kcmd.Terminate(this.killSignal)
		CPrintf(CYELLOW, "program terminated, signal(%v)", this.killSignal)
		this.kcmd = nil
	}
}

// when use func (this *TriggerEvent) strange things happened, wired
func (this *TriggerEvent) WatchEvent(evtC chan FSEvent, wg *sync.WaitGroup) {
	this.Start()
	for evt := range evtC {
		isMatch, err := ignore.Matches(evt.Name, this.Pattens)
		if err != nil {
			log.Fatal(err)
		}
		if !isMatch {
			continue
		}
		this.Stop()
		log.Printf("delay: %v", this.Delay)
		time.Sleep(this.delayDuration)
		this.Start()
	}
	this.Stop()
	wg.Done()
}

type FSEvent struct {
	Name string
}

type FWConfig struct {
	Description string         `yaml:"desc"`
	Triggers    []TriggerEvent `yaml:"triggers"`
	WatchPaths  []string       `yaml:"watch_paths"`
	WatchDepth  int            `yaml:"watch_depth"`
}

func fixFWConfig(in FWConfig) (out FWConfig, err error) {
	out = in
	for idx, trigger := range in.Triggers {
		outTg := &out.Triggers[idx]
		if trigger.Delay == "" {
			outTg.Delay = "100ms"
		}
		outTg.delayDuration, err = time.ParseDuration(outTg.Delay)
		if err != nil {
			return
		}
		if outTg.Signal == "" {
			outTg.Signal = "HUP"
		}
		outTg.killSignal = signalMaps[outTg.Signal]

		rd := ioutil.NopCloser(bytes.NewBufferString(strings.Join(outTg.Pattens, "\n")))
		// rd := ioutil.NopCloser(bytes.NewBufferString("*.exe"))
		patterns, er := ignore.ReadIgnore(rd)
		if er != nil {
			err = er
			return
		}
		outTg.matchPattens = patterns
	}
	if len(out.WatchPaths) == 0 {
		out.WatchPaths = append(out.WatchPaths, ".")
	}
	if out.WatchDepth == 0 {
		out.WatchDepth = 5
	}

	return
}

func readString(prompt, value string) string {
	fmt.Printf("[?] %s (%s) ", prompt, value)
	var s = value
	fmt.Scanf("%s", &s)
	return s
}

func genFWConfig() FWConfig {
	var (
		name    string
		command string
	)
	cwd, _ := os.Getwd()
	name = filepath.Base(cwd)
	name = readString("name:", name)

	for command == "" {
		command = readString("command:", "go test -v")
	}
	fwc := FWConfig{
		Description: fmt.Sprintf("Auto generated by fswatch [%s]", name),
		Triggers: []TriggerEvent{{
			Pattens: []string{"*.go", "*.c", "*.py"},
			Environ: map[string]string{
				"DEBUG": "1",
			},
			Command: command,
		}},
	}
	out, _ := fixFWConfig(fwc)
	return out
}

func ListAllDir(path string, depth int) (dirs []string, err error) {
	baseNumSeps := strings.Count(path, string(os.PathSeparator))
	err = filepath.Walk(path, func(path string, info os.FileInfo, err error) error {
		if info.IsDir() {
			base := info.Name()
			if base != "." && strings.HasPrefix(base, ".") { // ignore hidden dir
				return filepath.SkipDir
			}

			pathDepth := strings.Count(path, string(os.PathSeparator)) - baseNumSeps
			if pathDepth > depth {
				return filepath.SkipDir
			}
			dirs = append(dirs, path)
		}
		return nil
	})
	return
}

func UniqStrings(ss []string) []string {
	out := make([]string, 0, len(ss))
	m := make(map[string]bool, len(ss))
	for _, key := range ss {
		if !m[key] {
			out = append(out, key)
			m[key] = true
		}
	}
	return out
}

func IsDirectory(path string) bool {
	pinfo, err := os.Stat(path)
	return err == nil && pinfo.IsDir()
}

var fileModifyTimeMap = make(map[string]time.Time)

func IsChanged(path string) bool {
	pinfo, err := os.Stat(path)
	if err != nil {
		return true
	}
	mtime := pinfo.ModTime()
	if mtime.Sub(fileModifyTimeMap[path]) > time.Millisecond*100 { // 100ms
		fileModifyTimeMap[path] = mtime
		return true
	}
	return false
}

// visits here for in case of duplicate paths
func WatchPathAndChildren(w *fsnotify.Watcher, paths []string, depth int, visits map[string]bool) error {
	if visits == nil {
		visits = make(map[string]bool)
	}

	watchDir := func(dir string) {
		if visits[dir] {
			return
		}
		w.Watch(dir)
		log.Debug("Watch directory:", dir)
		visits[dir] = true
	}
	var err error
	for _, path := range paths {
		if visits[path] {
			continue
		}

		watchDir(path)
		dirs, er := ListAllDir(path, depth)
		if er != nil {
			err = er
			log.Warnf("ERR list dir: %s, depth: %d, %v", path, depth, err)
			continue
		}

		for _, dir := range dirs {
			watchDir(dir)
		}
	}
	return err
}

func drainEvent(fwc FWConfig) (globalEventC chan FSEvent, wg *sync.WaitGroup, err error) {
	globalEventC = make(chan FSEvent, 1)
	wg = &sync.WaitGroup{}
	evtChannls := make([]chan FSEvent, 0)
	// log.Println(len(fwc.Triggers))
	for _, tg := range fwc.Triggers {
		wg.Add(1)
		evtC := make(chan FSEvent, 1)
		evtChannls = append(evtChannls, evtC)
		go func(tge TriggerEvent) {
			tge.WatchEvent(evtC, wg)
		}(tg)

		// Can't write like this, the next loop tg changed, but go .. is not finished
		// go tg.WatchEvent(evtC, wg)
	}

	go func() {
		for evt := range globalEventC {
			for _, eC := range evtChannls {
				eC <- evt
			}
		}
		for _, eC := range evtChannls {
			close(eC)
		}
	}()
	return
}

func readFWConfig(path string) (fwc FWConfig, err error) {
	data, err := ioutil.ReadFile(FWCONFIG)
	if err != nil {
		return
	}
	err = yaml.Unmarshal(data, &fwc)
	if err != nil {
		return
	}
	fwc, err = fixFWConfig(fwc)
	// data, _ = json.MarshalIndent(fwc, "", "    ")
	// fmt.Println(string(data))
	return
}

func transformEvent(fsw *fsnotify.Watcher, evtC chan FSEvent) {
	for evt := range fsw.Event {
		if evt.IsCreate() && IsDirectory(evt.Name) {
			log.Info("Add watcher")
			fsw.Watch(evt.Name)
			continue
		}
		if evt.IsDelete() {
			log.Info("Remove watcher")
			fsw.RemoveWatch(evt.Name)
		}
		if !IsChanged(evt.Name) {
			continue
		}
		log.Printf("Changed: %s", evt.Name)
		evtC <- FSEvent{ // may panic here
			Name: evt.Name,
		}
	}
}

func InitFWConfig() {
	fwc := genFWConfig()
	data, err := yaml.Marshal(fwc)
	if err != nil {
		log.Fatal(err)
	}
	yn := readString(fmt.Sprintf("Save to file (%s)", FWCONFIG), "Y")
	if strings.ToLower(yn) == "y" {
		ioutil.WriteFile(FWCONFIG, data, 0644)
		fmt.Println("Saved!")
	} else {
		fmt.Println(string(data))
	}
}

func main() {
	version := flag.Bool("version", false, "Show version")
	flag.Parse()

	if *version {
		fmt.Println(VERSION)
		return
	}

	subCmd := flag.Arg(0)
	if subCmd == "" {
		if _, err := os.Stat(FWCONFIG); err == nil { // .fwc.yml exists
			subCmd = "start"
		} else {
			subCmd = "init"
		}
	}

	switch subCmd {
	case "init":
		InitFWConfig()
	case "start":
		fwc, err := readFWConfig(FWCONFIG)
		if err != nil {
			log.Fatal(err)
		}
		visits := make(map[string]bool)
		fsw, _ := fsnotify.NewWatcher()

		err = WatchPathAndChildren(fsw, fwc.WatchPaths, fwc.WatchDepth, visits)
		if err != nil {
			log.Println(err)
		}

		evtC, wg, err := drainEvent(fwc)

		sigOS := make(chan os.Signal, 1)
		signal.Notify(sigOS, syscall.SIGINT)

		go func() {
			<-sigOS
			CPrintf(CPURPLE, "Catch signal Interrupt!")
			close(evtC)
		}()
		go transformEvent(fsw, evtC)
		wg.Wait()
		CPrintf(CPURPLE, "Kill all running ... Done")
	}
}
